### ISSUE TITLE
Unable to retrieve configuration Parameters ihris-config from FHIR server (http://localhost:8080/hapi/fhir)

### ISSUE THREAD

**Issue by dagenius007** [iHRIS/iHRIS#462]
How do I start up the fhir server? There is no part in the docs that explains this.

cc @nobertmn.

**Comment by nobertmn** [comment]
From the error above, looks like the Parameters configuration file in (your_site)ig/fsh-generated/resources/Parameters-ihris-config.json has not been loaded into the fhir server. so the system is not seeing it.

**Comment by nobertmn** [comment]
Just in case, I would advise you do the following.. go to the iHRIS/tools folder.. and run these commands
node signConfig.js --key rsa_1024_priv.pem --config ../ihris-backend/(your_site_name)/ig/fsh-generated/resources/Parameters-ihris-config.json > ../ihris-backend/(your_site_name)/ig/fsh-generated/resources/Parameters-ihris-config-tmp.json && mv ../ihris-backend/(your_site_name)/ig/fsh-generated/resources/Parameters-ihris-config-tmp.json ../ihris-backend/(your_site_name)/ig/fsh-generated/resources/Parameters-ihris-config.json

then load the file to the fhir server

node load.js --server http://localhost:8080/hapi/fhir ../ihris-backend/ihris-uganda/ig/fsh-generated/resources/Parameters-ihris-config.json 

then restart the system

npm run start/dev

**Comment by nobertmn** [comment]
Sorry, the documentation is not full yet. but we will keep updating it.

**Comment by dagenius007** [comment]
I am getting 
*Unable to retrieve configuration Parameters ihris-config from FHIR server (http://localhost:8080/hapi/fhir)
Request failed with status code 404*

<img width="1512" alt="Screenshot 2023-08-24 at 06 02 51" src="https://github.com/iHRIS/iHRIS/assets/16763826/5e1f510f-25d3-4a89-a40c-52cc7d629f7a">

My server is up and running.

@nobertmn

**Comment by nobertmn** [comment]
That error comes if the system cannot find Parameters-ihris-config from your fhir server.  Ideally all the loading of resources should be happening automatically. but if it doesn't you need to run the instructions I provided you in the last comment. i.e

cd to (your_path_to)iHRIS/tools

then

node signConfig.js --key rsa_1024_priv.pem --config ../ihris-backend/(your_site_name)/ig/fsh-generated/resources/Parameters-ihris-config.json > ../ihris-backend/(your_site_name)/ig/fsh-generated/resources/Parameters-ihris-config-tmp.json && mv ../ihris-backend/(your_site_name)/ig/fsh-generated/resources/Parameters-ihris-config-tmp.json ../ihris-backend/(your_site_name)/ig/fsh-generated/resources/Parameters-ihris-config.json

then

node load.js --server http://localhost:8080/hapi/fhir ../ihris-backend/(your_site_name)/ig/fsh-generated/resources/Parameters-ihris-config.json

Then restart your server.

**Comment by nobertmn** [comment]
If have updated the docs to indicate the correct way to configure and run iHRIS, with a section specific to that.
