### ISSUE TITLE
iHRIS practitioner supplemental sections throws error

### ISSUE THREAD

**Issue by ApostleDreSong** [iHRIS/iHRIS#475]
Subject matter refers. Clicking on any of the supplemental sections like, "Add Education History" throws an error. It's really been hard getting anyone on your team to help figure out these errors.

<img width="1728" alt="Screenshot 2023-10-12 at 06 25 50" src="https://github.com/iHRIS/iHRIS/assets/18594373/c89d2440-1589-41fe-b4bf-5818cb60e3a3">
<img width="1728" alt="Screenshot 2023-10-12 at 06 23 36" src="https://github.com/iHRIS/iHRIS/assets/18594373/61d4b073-c638-4bf6-b40d-07f374fd58d5">

**Comment by ashaban** [comment]
Kindly share the error you are getting

**Comment by ApostleDreSong** [comment]
Please, see this loom video for context:

https://www.loom.com/share/17c4ff9fbe0747e9bbff03439dd89bfe?sid=249c7922-c946-4488-b74a-ebce4702c32f

**Comment by ApostleDreSong** [comment]
@ashaban, please let me know if you got my response and if you can replicate the same error. Thank you

**Comment by ashaban** [comment]
It does appear to me that you dont have StructureDefinition for Extension loaded into your hapi fhir server. To verify, run below API on your fhir server:
curl http://localhost:8081/hapi/fhir/StructureDefinition/Extension
replace 8081 with your hapi fhir server port number

**Comment by ApostleDreSong** [comment]
See the response for this - curl http://localhost:8080/hapi/fhir/StructureDefinition/Extension

`<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.25.2</center>
</body>
</html>`

**Comment by ashaban** [comment]
Then its missing and you need to load it. Here is the structuredefinition for extension
https://pastecode.dev/s/bcehfcgPBK
Download and save it to a file i.e extension.json
Load it to your fhir server with below commands
node iHRIS/tools/load.js --server http://localhost:8080/hapi/fhir extension.json
Or use whatever tools to load it to your HAPI FHIR server

**Comment by ApostleDreSong** [comment]
After loading extension.json into fhir. I tried adding Education history to practitioner and got the below error. For context, I am running fhir with docker and the url is http://localhost:8080/fhir without the "hapi" path.

`/Users/damilareademeso/Documents/miracle_ihris/ihris-backend/modules/fhir/fhirDefinition.js:25
        let subExpression = "http://hl7.org/fhir/StructureDefinition/" + field.type[0].code
                                                                                   ^

TypeError: Cannot read properties of undefined (reading '0')
    at /Users/damilareademeso/Documents/miracle_ihris/ihris-backend/modules/fhir/fhirDefinition.js:25:84
    at new Promise (<anonymous>)
    at Object._getFieldDefinition (/Users/damilareademeso/Documents/miracle_ihris/ihris-backend/modules/fhir/fhirDefinition.js:8:12)
    at /Users/damilareademeso/Documents/miracle_ihris/ihris-backend/modules/fhir/fhirDefinition.js:46:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.0.0`

**Comment by ashaban** [comment]
Try loading a recent image of docker please, what i know this issues were resolved by @nobertmn

**Comment by ApostleDreSong** [comment]
Not sure that this has been fixed. Please, see the attached. I am on the latest commit by @nobertmn 

<img width="925" alt="Screenshot 2023-10-13 at 08 27 54" src="https://github.com/iHRIS/iHRIS/assets/18594373/5dba994c-50cc-45d5-a23f-ab84fbf42e8d">
<img width="927" alt="Screenshot 2023-10-13 at 08 28 19" src="https://github.com/iHRIS/iHRIS/assets/18594373/d2b5d071-fd1c-4e6e-ad16-ce6641cc1f7d">

**Comment by nobertmn** [comment]
@ApostleDreSong  I think i know where the issue is. I will take a look and get back to you.

**Comment by nobertmn** [comment]
@ApostleDreSong I have fixed this

**Comment by ApostleDreSong** [comment]
Works now. Thank you @ashaban and @nobertmn
