### ISSUE TITLE
Core apps installation throws "invalid app" error

### ISSUE THREAD

**Issue by ApostleDreSong** [iHRIS/iHRIS#476]
I downloaded the zip file from the branch of the identity management app from the core-apps repo. I did not rename it. I uploaded it to the apps section and clicked on install but got an "invalid app" error message. Please, see the attached

<img width="1728" alt="Screenshot 2023-10-11 at 21 19 48" src="https://github.com/iHRIS/ihris-core-apps/assets/18594373/352395ac-fc88-48da-9e29-546577bf9199">

**Comment by ashaban** [comment]
You are getting this error because you are trying to install an app that was not made for iHRIS. Refer [here](https://ihris.github.io/iHRIS/dev/ihris_apps/) to learn more on iHRIS apps.
https://ihris.github.io/iHRIS/dev/ihris_apps/

**Comment by ApostleDreSong** [comment]
Okay. checking it out. Thank you

**Comment by ApostleDreSong** [comment]
Thank you so much. Works! 

<img width="1728" alt="Screenshot 2023-10-13 at 05 57 45" src="https://github.com/iHRIS/iHRIS/assets/18594373/5a4eaff8-5c3a-43c9-af9f-30fff7f018fd">

N.B: Can you update the Readme.MD of the core apps repo with the info here - https://ihris.github.io/iHRIS/dev/ihris_apps/
