### ISSUE TITLE
Questionnaire Bulk upload not working

### ISSUE THREAD

**Issue by ApostleDreSong** [iHRIS/iHRIS#477]
At the moment, bulk upload shows success but does not populate the practitioner's table. Please, see the below template that I got from the file folder in ihris-backend.
N.B: Users are not able to download a usable template from the practitioner's page.

[sampleInput.xlsx](https://github.com/iHRIS/iHRIS/files/12890992/sampleInput.xlsx)

**Comment by nobertmn** [comment]
This has to be customised on country/ implementation by implementation basis as it depends on the customisations of the fields you have in the system. so what you have there are more like place holders to let you know the functionality exists but this particular functionality behind has to be customised depending on your fields

**Comment by ApostleDreSong** [comment]
Okay. Thank you. Is there a guide that I can follow for bulk upload for the default fields in Practitioner?
