### ISSUE TITLE
Table Pagination not working as expected

### ISSUE THREAD

**Issue by ApostleDreSong** [iHRIS/iHRIS#480]
Tables containing large data sets break on the third page. Kindly see the attached video for context.

https://github.com/iHRIS/iHRIS/assets/18594373/eaaf860e-a39a-41af-ae4b-2e7f8a083a2e

**Comment by nobertmn** [comment]
Fixed here https://github.com/iHRIS/iHRIS/commit/f1038de6ce2300c834a8abbb461cbe24f59b14e5

**Comment by ApostleDreSong** [comment]
Weldone @nobertmn
