### ISSUE TITLE
Extension of extensions not showing up on the frontend

### ISSUE THREAD

**Issue by ApostleDreSong** [iHRIS/iHRIS#481]
Good day.

To replicate the issue raised in the subject, kindly add an extension to the Practitioner.name field, you can call it maideName. Also, create an extension under another extension e.g address under residence in iHRIS questionnaire. Save a sample practitioner and view the card. It does not show the data on the frontend. However, the data is saved in fhir.

Kindly see the attached screenshots.

Regards

<img width="1728" alt="Screenshot 2023-10-31 at 10 10 42" src="https://github.com/iHRIS/iHRIS/assets/18594373/7f8b91a5-f714-4487-a794-912fab2d4551">
<img width="1728" alt="Screenshot 2023-10-31 at 10 10 48" src="https://github.com/iHRIS/iHRIS/assets/18594373/6b7c6b11-563d-4509-a5a0-75650a80813f">
<img width="1728" alt="Screenshot 2023-10-31 at 10 13 33" src="https://github.com/iHRIS/iHRIS/assets/18594373/cdf18429-702c-4f9a-bcb5-cb76f17035b6">

**Comment by ashaban** [comment]
I have pushed a fix for this. Please verify

**Comment by ApostleDreSong** [comment]
Works now with fsh-sushi@2.7.0 but not with the latest version of sushi
